### ISSUE TITLE
Allow different PHP versions

### ISSUE THREAD

**Issue by phil-davis** [owncloud-ci/core#17]
We are trying to run a CI pipeline for data_exporter that will install ownCloud core 9.0.11 or 9.1.8 and then run the data export command(s) and check the output...

But when we use `owncloud-ci/core` to do the `install-server`  step the install complains that version 9.* of ownCloud does not support PHP7.1

Can this docker image be made to support different PHP versions?
e.g. 5.6 7.0 7.1 7.2 7.3
@patrickjahns

**Comment by individual-it** [comment]
needed for https://github.com/owncloud/data_exporter/issues/94

**Comment by patrickjahns** [comment]
Sure - you would need to expand the drone pipeline to have the script sit on top of various php version.
Easiest would be to utilize build-args and inject the base-image for the Dockerfile this way.

Maybe @tboerger has further feedback or different ideas ?

**Comment by phil-davis** [comment]
We have moved on, and there are PHP 7.4 and 8.* versions nowadays.
