### ISSUE TITLE
Ability to specify *.config.php files to be taken into account when installing

### ISSUE THREAD

**Issue by patrickjahns** [owncloud-ci/core#6]
Owncloud allows for providing various `*.config.php` files in the `config` folder that will be magically 🔮 merged into a final config.php file during the installation process.

Since this only is happening, during the installation process, it would be nice to allow for specifying arbitrary config files as plugin definition, that get copied to the owncloud/config folder before the install step is executed.

We could introduce a `configs` keyword for this

**Comment by tboerger** [comment]
This doesn't happen only on installation, that should always happen.

**Comment by patrickjahns** [comment]
> This doesn't happen only on installation, that should always happen.
interesting - need to test once more - encountered issue when dealing with objectstorage

**Comment by patrickjahns** [comment]
behavior observed as @tboerger suggested - the problem might have been that opcache was active in the ci containers and thus the changes where not immediatly considered
