### ISSUE TITLE
Waiting for oracle database is not waiting enough

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud-ci/core#9]
The port check seems to be insufficient to assure that the oracle database container is up.     

When doing the migration from jenkins to drone in core I tried to add this snippet for being sure it is up, but it resulted in an infinite loop.

```
  SQLPLUS=/usr/lib/oracle/12.2/client64/bin/sqlplus
      DATABASEUSER=autotest
      DATABASENAME='XE'
      for i in {1..48}
          do
              if "${SQLPLUS}" "${DATABASEUSER}/owncloud@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=$DATABASEHOST)(Port=1521))(CONNECT_DATA=(SID=XE)))" < /dev/null | grep 'Connected to'; then
                  break;
              fi
              sleep 5
          done
```

After the adding of oracle driver in owncloud-ci/php running core tests didn't fail so I assumed it is was not necessary at all. But now adding oracle to test matrix in apps like workflow I am getting an error ```ORA-01033  ORACLE initialization or shutdown in progress.```

cc @patrickjahns

**Comment by patrickjahns** [comment]
Thanks for reporting - if it works correctly please add a function for it to the script and call the function here:
https://github.com/owncloud-ci/core/blob/master/rootfs/usr/sbin/plugin.sh#L132
